name: ItemBroadcast
main: dev.pilati.itembroadcast.ItemBroadcast
version: 1.0
softdepend:
    - Vault
api-version: 1.16
commands:
   itembroadcast:
      usage: /<command>
      description: Send a item to all players online
permissions:
   ib.send:
      description: Give acess to ib command
      default: op 